"use client";

import { useState } from "react";
import { Copy, Check, AlertTriangle } from "lucide-react";

const stats = [
  { label: "Total Referred", value: "0" },
  { label: "Total Earnings", value: "$0" },
  { label: "Generated Volume", value: "$0" },
];

export default function ReferralTab() {
  const [slug, setSlug] = useState("");
  const [claimed, setClaimed] = useState(false);
  const [copied, setCopied] = useState(false);

  const refLink = `https://memequant.ai/ref/${slug}`;
  const isValidSlug = /^[a-zA-Z0-9_-]{2,24}$/.test(slug);

  const handleClaim = () => {
    if (isValidSlug) setClaimed(true);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(refLink);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="h-full overflow-auto p-6 space-y-6">
      <h1 className="text-white font-semibold text-lg">Referral Program</h1>

      {/* Slug Selection */}
      <div className="bg-bg-card rounded-xl border border-border p-5">
        <p className="text-white font-semibold text-sm mb-1">
          {claimed ? "Your Referral Link" : "Choose Your Referral Slug"}
        </p>
        <p className="text-text-secondary text-xs mb-3">
          {claimed
            ? "Share this link to earn 10% of all transaction fees from your referrals."
            : "Pick a unique slug for your referral URL."}
        </p>
        {!claimed && (
          <div className="flex items-center gap-2 mb-3">
            <AlertTriangle size={14} className="text-yellow-400 flex-shrink-0" />
            <p className="text-text-secondary text-xs">Once claimed, your referral slug cannot be changed.</p>
          </div>
        )}

        {/* Input row */}
        <div className="flex items-center gap-2 mb-2">
          <div className="flex items-center flex-1 bg-bg-secondary rounded-lg border border-border overflow-hidden">
            <span className="text-text-secondary text-sm pl-3 flex-shrink-0 select-none">
              memequant.ai/ref/
            </span>
            <input
              type="text"
              value={slug}
              onChange={(e) => !claimed && setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9_-]/g, ""))}
              readOnly={claimed}
              placeholder="your-slug"
              className={`flex-1 bg-transparent text-white text-sm py-2.5 pr-3 outline-none placeholder:text-text-secondary/50 ${
                claimed ? "cursor-default" : ""
              }`}
              maxLength={24}
            />
          </div>
          {!claimed ? (
            <button
              onClick={handleClaim}
              disabled={!isValidSlug}
              className={`px-4 py-2.5 rounded-lg text-sm font-medium transition-colors flex-shrink-0 ${
                isValidSlug
                  ? "bg-accent text-white hover:bg-accent/90"
                  : "bg-bg-secondary text-text-secondary cursor-not-allowed"
              }`}
            >
              Claim Slug
            </button>
          ) : (
            <button
              onClick={handleCopy}
              className="p-2.5 bg-bg-secondary hover:bg-white/5 rounded-lg transition-colors text-text-secondary hover:text-white flex-shrink-0"
            >
              {copied ? <Check size={16} className="text-positive" /> : <Copy size={16} />}
            </button>
          )}
        </div>

        {/* Preview / Claimed state */}
        {!claimed && slug.length > 0 && (
          <p className="text-text-secondary text-xs">
            Preview: <span className="text-white font-mono">{refLink}</span>
          </p>
        )}
        {copied && claimed && <p className="text-positive text-xs mt-1.5">Copied to clipboard!</p>}
      </div>

      {/* Stat Cards */}
      <div className="grid grid-cols-3 gap-4">
        {stats.map((s) => (
          <div key={s.label} className="bg-bg-card rounded-xl border border-border p-4">
            <p className="text-text-secondary text-xs mb-1">{s.label}</p>
            <p className="text-white text-xl font-semibold">{s.value}</p>
          </div>
        ))}
      </div>

      {/* Info */}
      <p className="text-text-secondary text-sm">
        Earn 10% of all transaction fees generated by your referrals. Paid in real-time.
      </p>

      {/* Table */}
      <div className="bg-bg-card rounded-xl border border-border p-5">
        <table className="w-full text-sm">
          <thead>
            <tr className="text-text-secondary text-xs">
              <th className="text-left py-2 font-medium">User</th>
              <th className="text-left py-2 font-medium">Joined</th>
              <th className="text-right py-2 font-medium">Trades</th>
              <th className="text-right py-2 font-medium">Earned</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td colSpan={4} className="py-8 text-center text-text-secondary text-sm">
                No referrals yet
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}
